// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using itec420.Models;

#nullable disable

namespace itec420.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250513205805_FirstCreate")]
    partial class FirstCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("itec420.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentDescription = "A",
                            DepartmentName = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentDescription = "B",
                            DepartmentName = "Neurology"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentDescription = "C",
                            DepartmentName = "Oncology"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentDescription = "D",
                            DepartmentName = "Dermatology"
                        });
                });

            modelBuilder.Entity("itec420.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoctorDepartment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PicOfDoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorDepartment = "Cardiology",
                            DoctorName = "Michael Jordan",
                            PicOfDoc = "/img/1.png"
                        },
                        new
                        {
                            Id = 2,
                            DoctorDepartment = "Neurology",
                            DoctorName = "Jalen Brunson",
                            PicOfDoc = "/img/2.png"
                        },
                        new
                        {
                            Id = 3,
                            DoctorDepartment = "Cardiology",
                            DoctorName = "Lebron James",
                            PicOfDoc = "/img/3.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
